# Generated by Django 4.1.5 on 2023-01-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='left_key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree_menu.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='right_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
