# Generated by Django 4.1.5 on 2023-01-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0002_alter_item_left_key_alter_item_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'menu')},
        ),
    ]
